# 服务配置
server:
  port: 9001
# spring 配置
spring:
  application:
    name: hrm-cpmpany
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.189.212:3306/hrm?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: sdbs
  jpa:
    database: mysql
    show-sql: true
    open-in-view: true

#  swagger2 项目配置
swagger2:
  author: yangtk
  url:
  email: 1061203621@qq.com
  title: 公司Api文档
  desc: 公司管理系统
  version: v1.0