# 服务配置
server:
  port: 9001
# spring 配置
spring:
  application:
    name: hrm-cpmpany
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdb:mysql://localhost:3306/hrm?useUnicode=true&characterEncoding=utf8
    username: root
    password: sdbs
  jpa:
    database: mysql
    show-sql: true
    open-in-view: true